### ISSUE TITLE
Flows go inactive and continue to show green

### ISSUE THREAD

**Issue by chrisfleck** [octoblu/issues#81]
I have frequent occurrences where my flow go dormant even after restarting ( seems like overnight or some time delay ). Also in many cases the deploy status continues to show green.

**Comment by iamruinous** [comment]
Flow service was completely down, and we found a couple of other issues in the flow-runner. If you have any problems with the flow stopping in the future, send us the flow id and don't restart the flow so we can debug it.

Thanks!

**Comment by chrisfleck** [comment]
Here is a flow that shows green. But does not run.
I have not restarted it
https://app.octoblu.com/design/9369d140-d25b-11e4-a50d-d3d8c9499cdb

**Comment by iamruinous** [comment]
```
{"log":"UUID FAILED AUTHENTICATION! { error: 'rate limit exceeded 52.25.165.184' }\n","stream":"stdout","time":"2015-06-09T17:51:44.421418101Z"}
```

We found that a lot of flows are getting rate limited when trying to reconnect to meshblu. Since all the flows are running on just a handful of machines it triggers the connection rate limit. We added those machines to the unthrottled ips list of Meshblu, but are working on a better solution that allows the auto-scaling flow cluster to add new machines dynamically as needed.

Thanks for the flow id, you should be able to restart this flow now.

**Comment by chrisfleck** [comment]
thx
